# Generated by Django 4.1.2 on 2022-10-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo", name="latitude_atual", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="veiculo", name="longitude_atual", field=models.FloatField(),
        ),
    ]
